apiVersion: v1
kind: Service
metadata:
    name: master-node-port
spec:
    type: NodePort
    ports:
      # Other pods within the cluster can communicate with this pod on the specified port
      # NodePort is the default setting if the port field is not specified
      - port: 3050
        # container port
        targetPort: 5439
        # host port (routes to container port) needs to be between 30000 and 32767
        # nodePort: 31515    <-- if not set, accidental free port will be chosen
    selector:
        app: db_master

# should be possible from node:
    # telnet ip_of_node 31324
    # telnet ip_of_pod  5439
